import { Input, Table, Card, Button, Dropdown, type MenuProps } from 'antd';
import { useEffect, useState } from 'react';
import axios from 'axios';
import type { ColumnsType } from 'antd/es/table';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

import { CiSearch } from 'react-icons/ci';
import {
  PrinterOutlined,
  DownloadOutlined,
  DownOutlined,
} from '@ant-design/icons';

type RouteTaxi = {
  id: number;
  Routes: string;
  Taxis: number;
  RegisteredTaxis: number;
  WaitingCount: number;
  Dispatcher?: string;
};

export default function TaxAssignment() {
  const [searchText, setSearchText] = useState('');
  const [routeTaxiList, setRouteTaxiList] = useState<RouteTaxi[]>([]);
  const [loading, setLoading] = useState(false);

  const columns: ColumnsType<RouteTaxi> = [
    {
      title: 'ROUTE',
      dataIndex: 'Routes',
      key: 'Routes',
      width: '20%',
    },
    {
      title: 'AVAILABLE TAXIS',
      dataIndex: 'Taxis',
      key: 'Taxis',
      align: 'center' as const,
      width: '15%',
    },
    {
      title: 'REGISTERED TAXIS',
      dataIndex: 'RegisteredTaxis',
      key: 'RegisteredTaxis',
      align: 'center' as const,
      width: '15%',
    },
    {
      title: 'WAITING PASSENGERS',
      dataIndex: 'WaitingCount',
      key: 'WaitingCount',
      align: 'center' as const,
      width: '15%',
      render: (value: number | null) => value ?? 0,
    },
    {
      title: 'DISPATCHER',
      dataIndex: 'Dispatcher',
      key: 'Dispatcher',
      width: '20%',
      render: (name) => name || '—',
    },
  ];

  const filteredData = routeTaxiList.filter((item) =>
    item.Routes.toLowerCase().includes(searchText.toLowerCase())
  );

  const fetchTaxiAssignment = async () => {
    const token = localStorage.getItem('token');
    if (!token) return;

    setLoading(true);
    try {
      const res = await axios.get(
        'http://localhost:5000/taxiAssignment/allStationInfo',
        {
          headers: { Authorization: `Bearer ${token}` },
        }
      );
      setRouteTaxiList(res.data);
    } catch (err) {
      console.error('Failed to fetch station info:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchTaxiAssignment();
    const interval = setInterval(fetchTaxiAssignment, 10000);
    return () => clearInterval(interval);
  }, []);

  const handlePrint = () => {
    const printContent = document.getElementById('printable-table');
    const printWindow = window.open('', '_blank');

    if (printWindow && printContent) {
      printWindow.document.write(`
        <html>
          <head>
            <title>Taxi Assignment Report</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 40px; }
              h1 { color: #333; border-bottom: 2px solid #1890ff; padding-bottom: 10px; }
              .report-info { margin: 20px 0; color: #666; }
              table { width: 100%; border-collapse: collapse; margin-top: 20px; }
              th { background-color: #f5f5f5; text-align: left; padding: 12px; border: 1px solid #ddd; font-weight: bold; }
              td { padding: 10px; border: 1px solid #ddd; }
              .footer { margin-top: 30px; color: #999; font-size: 12px; text-align: center; }
              .text-center { text-align: center; }
              @page { size: A4 landscape; margin: 20mm; }
              @media print {
                body { margin: 0; }
                table { page-break-inside: auto; }
                tr { page-break-inside: avoid; page-break-after: auto; }
              }
            </style>
          </head>
          <body>
            <h1>Taxi Assignment Report</h1>
            <div class="report-info">
              Generated on: ${new Date().toLocaleString()}<br>
              Total Routes: ${filteredData.length}
            </div>
            <table>
              <thead>
                <tr>
                  <th>Route</th>
                  <th>Available Taxis</th>
                  <th>Registered Taxis</th>
                  <th>Waiting Passengers</th>
                  <th>Dispatcher</th>
                </tr>
              </thead>
              <tbody>
                ${filteredData
                  .map(
                    (item) => `
                  <tr>
                    <td>${item.Routes}</td>
                    <td class="text-center">${item.Taxis}</td>
                    <td class="text-center">${item.RegisteredTaxis}</td>
                    <td class="text-center">${item.WaitingCount}</td>
                    <td>${item.Dispatcher || '—'}</td>
                  </tr>
                `
                  )
                  .join('')}
              </tbody>
            </table>
            <div class="footer">
              Report generated by TaxiLink System
            </div>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.focus();
      setTimeout(() => {
        printWindow.print();
        printWindow.close();
      }, 250);
    } else {
      window.print();
    }
  };

  const handleExportCSV = () => {
    const headers = [
      'Route',
      'Available Taxis',
      'Registered Taxis',
      'Waiting Passengers',
      'Dispatcher',
    ];

    const csvRows = [];

    csvRows.push(headers.join(','));

    filteredData.forEach((item) => {
      const row = [
        `"${item.Routes.replace(/"/g, '""')}"`,
        item.Taxis,
        item.RegisteredTaxis,
        item.WaitingCount,
        `"${(item.Dispatcher || 'N/A').replace(/"/g, '""')}"`,
      ];
      csvRows.push(row.join(','));
    });

    const csvString = csvRows.join('\n');

    const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `taxi-assignment-${
      new Date().toISOString().split('T')[0]
    }.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  const handleExportExcel = async () => {
    try {
      const XLSX = await import('xlsx');

      const excelData = filteredData.map((item) => ({
        Route: item.Routes,
        'Available Taxis': item.Taxis,
        'Registered Taxis': item.RegisteredTaxis,
        'Waiting Passengers': item.WaitingCount,
        Dispatcher: item.Dispatcher || 'N/A',
      }));

      const worksheet = XLSX.utils.json_to_sheet(excelData);

      const workbook = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(workbook, worksheet, 'Station Report');

      const maxWidth = filteredData.reduce(
        (w, r) => Math.max(w, r.Routes.length),
        10
      );
      if (worksheet['!cols'] === undefined) worksheet['!cols'] = [];
      worksheet['!cols'] = [
        { wch: maxWidth },
        { wch: 15 },
        { wch: 15 },
        { wch: 18 },
        { wch: 15 },
      ];

      XLSX.writeFile(
        workbook,
        `station-report-${new Date().toISOString().split('T')[0]}.xlsx`
      );
    } catch (error) {
      console.error('Error exporting Excel:', error);
      alert('Excel export failed, downloading CSV instead');
      handleExportCSV();
    }
  };

  const handleExportJSON = () => {
    const jsonString = JSON.stringify(filteredData, null, 2);
    const blob = new Blob([jsonString], { type: 'application/json' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `taxi-assignment-${
      new Date().toISOString().split('T')[0]
    }.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  const handleExportPDF = () => {
    const doc = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: 'a4',
    });

    doc.setFontSize(18);
    doc.text('Taxi Assignment Report', 14, 15);

    doc.setFontSize(10);
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 22);

    const tableColumn = [
      'Route',
      'Available Taxis',
      'Registered Taxis',
      'Waiting Passengers',
      'Dispatcher',
    ];

    const tableRows = filteredData.map((item) => [
      item.Routes,
      item.Taxis ?? 0,
      item.RegisteredTaxis ?? 0,
      item.WaitingCount ?? 0,
      item.Dispatcher || '—',
    ]);

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 28,
      styles: { fontSize: 9 },
      headStyles: { fillColor: [24, 144, 255] },
      columnStyles: {
        1: { halign: 'center' },
        2: { halign: 'center' },
        3: { halign: 'center' },
      },
    });

    doc.save(`taxi-assignment-${new Date().toISOString().split('T')[0]}.pdf`);
  };

  const exportMenuItems: MenuProps['items'] = [
    {
      key: 'excel',
      label: 'Export as Excel',
      onClick: handleExportExcel,
    },
    {
      key: 'pdf',
      label: 'Export as PDF',
      onClick: handleExportPDF,
    },
    {
      key: 'json',
      label: 'Export as JSON',
      onClick: handleExportJSON,
    },
  ];

  return (
    <>
      <Card className="shadow-sm border-0 mb-6" bodyStyle={{ padding: 16 }}>
        <div className="flex justify-between items-center">
          <Input
            value={searchText}
            onChange={(e) => setSearchText(e.target.value)}
            placeholder="Search by route name..."
            prefix={<CiSearch className="text-gray-400" />}
            allowClear
            className="rounded-lg h-10"
            style={{ width: 300 }}
          />

          <div className="flex space-x-3">
            <Button
              icon={<PrinterOutlined />}
              onClick={handlePrint}
              className="flex items-center"
            >
              Print
            </Button>

            <Dropdown menu={{ items: exportMenuItems }} placement="bottomRight">
              <Button
                type="primary"
                icon={<DownloadOutlined />}
                className="flex items-center"
              >
                Export <DownOutlined className="ml-1" />
              </Button>
            </Dropdown>
          </div>
        </div>
      </Card>

      <Card
        className="shadow-sm border-0"
        bodyStyle={{ padding: 0 }}
        id="printable-table"
        title={
          <div className="text-lg font-medium">
            Report Overview
            <span className="text-sm text-gray-500 ml-2">
              ({filteredData.length} routes)
            </span>
          </div>
        }
      >
        <Table
          columns={columns}
          dataSource={filteredData}
          rowKey="id"
          loading={loading}
          size="middle"
          bordered={false}
          pagination={{
            showSizeChanger: true,
            showQuickJumper: true,
            showTotal: (total) => `Total ${total} routes`,
            pageSizeOptions: ['10', '20', '50', '100'],
            defaultPageSize: 10,
            responsive: true,
            className: 'px-4',
          }}
          scroll={{ x: true }}
          className="custom-table"
        />
      </Card>
    </>
  );
}
